Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AngularMVC.Models
{
    public class Album
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AlbumID { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string AlbumName { get; set; }


        [Display(Name = "Number of Tracks")]
        public Int32 NumberOfTracks { get; set; }

        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Year of Release")]
        public Int32 ReleaseYear { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Cost { get; set; }
        public string Genre { get; set; }

        public int? ArtistID { get; set; }

        public Artist Artist { get; set; }
        public ICollection<Track> Tracks { get; set; }
    }
}

Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;

namespace AngularMVC.Models
{
    public class Artist
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ArtistID { get; set; }

        [Required]
        public string ArtistName { get; set; }

        public ICollection<Album> Albums { get; set; }
        //public IPagedList<Album> Albums { get; set; }
    }
}

Models/Track.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AngularMVC.Models
{
    public class Track
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TrackID { get; set; }

        [Required]
        public string TrackName { get; set; }
        public int? AlbumID { get; set; }
        public Album Album { get; set; }
    }
}

Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AngularMVC.DB;
using Newtonsoft.Json;
using AngularMVC.Models;

namespace AngularMVC.Controllers
{
    public class ArtistController : Controller
    {
        private MusicContext context = new MusicContext();
        // GET: Artist
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ContentResult GetArtists()
        {
            var artists = context.Artists.Include("Albums.Tracks").ToList();
            var list = JsonConvert.SerializeObject(artists, Formatting.None, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
            return Content(list, "application/json");
        }

        public string InsertArtist(Artist artist)
        {
            if(artist != null)
            {
                using (context)
                {
                    context.Artists.Add(artist);
                    context.SaveChanges();
                    return "Artist successfully added!";
                }
            }
            else
            {
                return "Error inserting artist. Please try again.";
            }
        }
    }
}

Views/Artist/Index.cshtml

@{
    ViewBag.Title = "Index";
}

@section scripts{
    <script src="~/ArtistClient.js"></script>

    <script>
        $(function () {
            $('body').on('click', '.tog span', function () {
                if ($(this).text() == '+') {
                    $(this).text('-');
                }
                else {
                    $(this).text('+');
                }
                $(this).closest('tr').next('tr').toggle()
            });
        });
    </script>
}


<div ng-app="ArtistApp" class="container">
    <br />
    <br />
    <input type="text" placeholder="Search Artists" ng-model="searchArtists" />
    <br />
    <br />
    <div ng-controller="ArtistController">
        <table class="tableData">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        <a href="#" ng-click="sortBy = 'ArtistID'; reverse = !reverse">
                            <span class="sortOrder" ng-show="sortBy == 'ArtistID'" ng-class="{reverse:reverse}"></span>
                            Artist ID
                        </a>
                    </th>
                    <th>
                        <a href="#" ng-click="sortBy = 'ArtistName'; reverse = !reverse">
                            <span class="sortOrder" ng-show="sortBy == 'ArtistName'" ng-class="{reverse: reverse}"></span>
                            Artist Name
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody ng-repeat="a in artists | filter: searchArtists | orderBy: sortBy:reverse">
                <tr>
                    <td class="tog"><span>+</span></td>
                    <td>

                        {{a.ArtistID}}
                    </td>
                    <td>
                        {{a.ArtistName}}
                    </td>
                </tr>
                <tr class="child">
                    <td></td>
                    <td colspan="4">
                        <table class="tableData">
                            <tr>
                                <th></th>
                                <th>
                                    <a href="#" ng-click="sortBy = 'AlbumName'; reverse = !reverse">
                                        <span class="sortOrder" ng-show="sortBy == 'AlbumName'" ng-class="{reverse:reverse}"></span>
                                        Album Name
                                    </a>
                                </th>
                                <th>Number of Tracks</th>
                                <th>Release Year</th>
                                <th>Genre</th>
                            </tr>
                            <tbody id="albumBody" ng-repeat="l in a.Albums | orderBy: sortBy:reverse">
                                <tr ng-class-even="even" ng-class-odd="odd">
                                    <td class="tog"><span>+</span></td>
                                    <td>
                                        {{l.AlbumName}}
                                    </td>
                                    <td>
                                        {{l.NumberOfTracks}}
                                    </td>
                                    <td>{{l.ReleaseYear}}</td>
                                    <td>{{l.Genre}}</td>
                                </tr>
                                <tr class="child">
                                    <td></td>
                                    <td colspan="3">
                                        <table class="tableData" border="0" cellpadding="0" cellspacing="0">
                                            <tr>
                                                <th>Tracks</th>
                                            </tr>
                                            <tr ng-repeat="t in l.Tracks">
                                                <td>{{t.TrackName}}</td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Artists", "Index", "Artist", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Albums", "Index", "Album")</li>
                    <li>@Html.ActionLink("Tracks", "Index", "Track")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>